Feature/timeseries chart
iteratec/OpenSpeedMonitor pull request #318
Opened 2020-01-13 11:58 UTC by mekiert

2020-01-14 12:04 UTC, BennyLi commented
Local testing looks good. Just one points from local testing:

- [ ] The mouse to data point association isn't as good as it was before (in the old graph). In the old graph the nearest dot was always on the line that was next to the mouse pointer. In the new graph it is the nearest point to the marker line, which makes it very difficult to get to some data points in the graph. Well, this is not related to this ticket. So maybe we should consider to open a bug issue for this.

2020-01-14 12:04 UTC, BennyLi requested changes

2020-01-14 12:04 UTC, BennyLi commented on frontend/src/app/modules/time-series/services/line-chart.service.ts
> +  // }
Remove unused code.

2020-01-14 12:04 UTC, BennyLi commented on grails-app/i18n/messages.properties
> +frontend.de.iteratec.chart.contextMenu.screenshot=Screen Shot
Please change it to `Screenshot`

2020-01-15 12:19 UTC, mekiert commented on frontend/src/app/modules/time-series/services/line-chart.service.ts
> +  // }
Done.

2020-01-15 12:43 UTC, mekiert commented on grails-app/i18n/messages.properties
> +frontend.de.iteratec.chart.contextMenu.screenshot=Screen Shot
Done.

2020-01-15 13:42 UTC, BennyLi approved these changes

2020-01-20 14:56 UTC, merged