Time series chart data restriction
iteratec/OpenSpeedMonitor pull request #348
Opened 2020-05-19 12:00 UTC by DanielSteger

- Time series chart data restriction (#307)
- Refactoring of time series module
- Fixed zoom in time series chart (#344)

2020-06-22 11:21 UTC, BennyLi commented on frontend/src/app/modules/time-series/components/time-series-chart/time-series-chart.component.html
> +    <osm-spinner [spinnerId]="'time-series-line-chart-spinner'"></osm-spinner>
Are both quotes needed?

2020-06-22 11:21 UTC, BennyLi commented on frontend/src/app/modules/time-series/components/time-series-chart/time-series-chart.component.html
> +          <input (focusout)="validateInputValues('min', 'max', measurandGroup.key); redraw(false)"
`redraw(false)` is kinda complicated to read without an IDE that shows the parameter name.
First question that was in my mind: Why call redraw if it shouldn't redraw?

If we trace it down, the function definition is `redraw(updateAllData: boolean)`. So ok, it should update all data. And how does it do that? It just passes the boolean argument to the LineChartService
`this.lineChartService.drawLineChart(this.timeSeriesResults, this.selectedTrimValues, updateAllData);`
In here two things happen:
```
...
    if (updateAllData) {
      this.lineChartLegendService.setLegendData(incomingData);
    }
...
    this.lineChartEventService.addBrush(chartContentContainer, this._width, this._height, this.Y_AXIS_WIDTH, xScale,
      data, dataTrimValues, this.lineChartLegendService.legendDataMap, !updateAllData);
...
```
In the second call the value of `updateAllData` is inverted. The parameter of the `addBrush` function used is `keepZoom`, which is a total different thing. 🤯

I really want this to be refactored. Maybe we should open an improvement task for this and the create a new PR just for this. 

Take a look at this for a funny reference: https://www.informit.com/articles/article.aspx?p=1392524

2020-06-22 11:21 UTC, BennyLi commented on frontend/src/app/modules/time-series/components/time-series-chart/time-series-chart.component.spec.ts
> +    expect(component).toBeTruthy();
More tests to come?
Otherwise remove the file. :)

2020-06-22 11:21 UTC, BennyLi commented on frontend/src/app/modules/time-series/components/time-series-chart/time-series-chart.component.ts
> +  ngOnChanges(changes: SimpleChanges): void {
The `changes` parameter is not used for evaluation of the changes. Currently this shouldn't be a problem as we only have one `@Input` value. But if a add another this method will be called twice. Is this intended?

Checkout this article: https://dev.to/nickraphael/ngonchanges-best-practice-always-use-simplechanges-always-1feg

2020-06-22 11:21 UTC, BennyLi commented on frontend/src/app/modules/time-series/components/time-series-chart/time-series-chart.component.ts
> +  private validateInputValuesByType(type: string, inputRangeMin: number, inputRangeMax: number, measurandGroup: string): void {
This method does not validate, it does correct the values.
Maybe it should be renamed?

2020-06-22 11:21 UTC, BennyLi commented on frontend/src/app/modules/time-series/components/time-series-chart/time-series-chart.component.ts
> +  validateInputValues(selectedInput: string, otherInput: string, measurandGroup: string): void {
This method does not validate, it does correct the values.
Maybe it should be renamed?

2020-06-22 11:21 UTC, BennyLi commented on frontend/src/app/modules/time-series/services/chart-feature-services/line-chart-draw.service.spec.ts
> +    expect(service).toBeTruthy();
More tests to come?

2020-06-22 11:31 UTC, DanielSteger commented on frontend/src/app/modules/time-series/components/time-series-chart/time-series-chart.component.html
> +    <osm-spinner [spinnerId]="'time-series-line-chart-spinner'"></osm-spinner>
Oddly enough, yes. Otherwise it isn't recognized as a string in this case.

2020-06-22 12:17 UTC, BennyLi commented on frontend/src/app/modules/time-series/services/chart-feature-services/line-chart-event.service.spec.ts
> +    const service: LineChartEventService = TestBed.get(LineChartEventService);
More tests to come?

2020-06-22 12:17 UTC, BennyLi commented on frontend/src/app/modules/time-series/services/chart-feature-services/line-chart-event.service.ts
> +  private DOT_HIGHLIGHT_RADIUS = 5;
In the LineChartDrawService is a variable calles `private _DOT_RADIUS`. Why no `_` prefix here?

2020-06-22 12:17 UTC, BennyLi commented on frontend/src/app/modules/time-series/services/chart-feature-services/line-chart-event.service.ts
> +          .buildUrlByOption(d.wptInfo, this.urlBuilderService.options.waterfall));
I know this is legacy stuff, but...  Why are there some explicit functions (like `buildSummaryUrl`) on the `urlBuilderService` and some/one generic ones like in this line? Couldn't this be refactored?

2020-06-22 12:17 UTC, BennyLi commented on frontend/src/app/modules/time-series/services/chart-feature-services/line-chart-event.service.ts
> +    if (this.lineChartDrawService.xAxisCluster.length < 2) {
Please make it clear why this is a jump-off criterion.

2020-06-22 12:17 UTC, BennyLi commented on frontend/src/app/modules/time-series/services/chart-feature-services/line-chart-legend.service.spec.ts
> +    const service: LineChartLegendService = TestBed.get(LineChartLegendService);
More tests to come?

2020-06-22 12:17 UTC, BennyLi commented on frontend/src/app/modules/time-series/services/chart-feature-services/line-chart-legend.service.ts
> +  private focusedLegendEntry: string;
Please prefix this private property with an underscore `_`

2020-06-22 12:17 UTC, BennyLi commented on frontend/src/app/modules/time-series/services/chart-feature-services/line-chart-legend.service.ts
> +  private _legendDataMap: { [key: string]: { [key: string]: (boolean | string) } } = {};
Move this property up to the rest

2020-06-22 19:04 UTC, BennyLi commented on frontend/src/app/modules/time-series/services/chart-feature-services/line-chart-scale.service.spec.ts
> +    const service: LineChartScaleService = TestBed.get(LineChartScaleService);
More tests to come?

2020-06-22 19:11 UTC, BennyLi requested changes

2020-06-22 19:11 UTC, BennyLi commented on frontend/src/app/modules/time-series/services/chart-feature-services/line-chart-scale.service.ts
> +      const min: number = dataTrimValues.min[key] ? Math.max(dataTrimValues.min[key], 0) : 0;
Duplicate code (see line 38).

2020-06-22 19:11 UTC, BennyLi commented on frontend/src/app/modules/time-series/services/chart-feature-services/line-chart-scale.service.ts
> +      const min: number = dataTrimValues.min[key] ? Math.max(dataTrimValues.min[key], 0) : 0;
The whole function looks pretty the same, except for line 61 / line 39. Maybe this could be refactored!

2020-06-22 19:11 UTC, BennyLi commented on frontend/src/app/modules/time-series/services/line-chart-data.service.spec.ts
> +    const service: LineChartDataService = TestBed.get(LineChartDataService);
More tests to come?

2020-06-22 19:11 UTC, BennyLi commented on frontend/src/app/modules/time-series/services/line-chart.service.spec.ts
> +    const service: LineChartService = TestBed.get(LineChartService);
More tests to come?

2020-06-22 19:11 UTC, BennyLi commented on frontend/src/app/modules/time-series/services/url-builder.service.spec.ts
> +    const service: UrlBuilderService = TestBed.get(UrlBuilderService);
More tests to come?

2020-06-23 19:49 UTC, BennyLi approved these changes
Good work! 🎉

2020-06-24 07:17 UTC, merged